### ISSUE TITLE
MapEntry throwing `Public property [$location] not found on component`

### ISSUE THREAD

**Issue by LukeSavefrogs** [dotswan/filament-map-picker#84]
## Description
I added the `MapEntry` to an Infolist as said in the docs:

```
MapEntry::make('location')
    ->label('Map')
    ->columnSpanFull()

    // Controls
    ->showFullscreenControl(true)
    ->showZoomControl(true)
```

This raises the following error
![Image](https://github.com/user-attachments/assets/d234b43a-5caf-447a-9a55-6caf1dbb7499)

## Version information 
- Laravel: `11.44.7`
- Filament: `3.3.13`
- FilamentMapPicker: `1.8.2`

**Comment by amendozaaguiar** [comment]
Same problem 😢

**Comment by LukeSavefrogs** [comment]
> Same problem 😢

Can you confirm you're using the same versions (PHP, Filamenti, FilamentMapPicker)?

**Comment by mohaphez** [comment]
Hi everyone,

The issue has been resolved, and the package has been updated to version 1.8.4.
Please update to the latest version at your convenience.

If you encounter any issues or have questions, feel free to reach out.

Thanks!

**Comment by LukeSavefrogs** [comment]
> Hi everyone,
> 
> The issue has been resolved, and the package has been updated to version 1.8.4. Please update to the latest version at your convenience.
> 
> If you encounter any issues or have questions, feel free to reach out.
> 
> Thanks!

Sadly, the problem is still there...

```php
MapEntry::make('location')
    ->label('Mappa')
    ->columnSpanFull()

    // Controls
    ->showFullscreenControl(true)
    ->showZoomControl(true)

    // GeoMan Integration (if needed for viewing)
    ->geoMan(true)
    ->geoManEditable(false),
```


![Image](https://github.com/user-attachments/assets/0fbd6efa-049a-4272-9d41-b3bba17fbe4a)

**Comment by mohaphez** [comment]
Hi @LukeSavefrogs 

Are you sure you updated the package, ran `php artisan filament:assets`, and did a hard refresh in your browser to load the new JS file?

**Comment by LukeSavefrogs** [comment]
> Hi [@LukeSavefrogs](https://github.com/LukeSavefrogs)
> 
> Are you sure you updated the package, ran `php artisan filament:assets`, and did a hard refresh in your browser to load the new JS file?

I updated the package to `v1.8.4` and even changed browser, but it still happens. Don't know why

**Comment by LukeSavefrogs** [comment]
I just noticed that only the css resource has been updated in the `public/` folder, not the JS file, even though I ran the `php artisan filament:assets`

**Comment by LukeSavefrogs** [comment]
> [@mohaphez](https://github.com/mohaphez) I just noticed that only the css resource has been updated in the `public/` folder, not the JS file, even though I ran the `php artisan filament:assets`

I tried forcefully changing the contents of the js file in the `public` folder with those from the [v1.8.4 file](https://github.com/dotswan/filament-map-picker/blob/0dbc86e2e59991d06a55d5e8025b653d63f4a118/resources/dist/filament-map-picker.js) and the issue vanished. Why was this file not updated with the package, like the css file was?

**Comment by ayech0x2** [comment]
I'm getting the same problem
